baseURL: "https://sonaljain2212.com"
languageCode: "en-us"
title: "Sonal Jain"

googleanalytics: UA-167646412-8
disqusShortname: 
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"
    
  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Sonal Jain"
  profession: "Machine Learning and Data Science enthusiast"
  github: "https://github.com/sonaljain2212"
  linkedin: "https://www.linkedin.com/in/sjain2212/"
  instagram: "https://www.instagram.com/sonal_jain_22/"
  facebook: "https://www.facebook.com/profile.php?id=100009302106683"


  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Sonal, a passionate Data enthusiast. I always thrive to work on end to end ML products which develop sustainable and scalable social and technical systems to create impact. I can make your data tell a story."
  descripe_l2_person: "Check out my recent ML 30 day challenge [here](https://github.com/sonaljain2212/30DaysOfML)"
  skills:
    - name: Python
      percentage: 90
    - name: MySQL
      percentage: 85
    - name: R
      percentage: 65
    - name: Java
      percentage: 50

  # Experience
  disable_experience: false
  experience:
    - company: "Quantiphi Inc."
      role: "Data Science Consultant Intern"
      startdate: Aug 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Accomplished 95% reduction in manual efforts, time, and cost by developing tool for DOCUMENT processing using Machine Learning and Google Cloud Platform. 
        #- point: Developed 8 critical features to classify, extract, translate, summarize, search documents.
    - company: "Tata Consultancy Services"
      role: "System Engineer"
      startdate: Oct 2016
      enddate: Jul 2019
      featuredpoints:
#         - point: Developed Recommendation System to recommend courses to TCS employees for increasing competency.
        - point: Led a team of 5 and developed Selenium automation testing framework for test banking mobile application and website.
#     - company: "Northeastern University"
#       role: "Teaching Assitant"
#       startdate: Jan 2020
#       enddate: Apr 2021
#       featuredpoints:
#         - point: Worked as a TA for Mathematics of Data Models and helped the students understand the statistical modeling, hypothesis testing and math behind the ML models.
#         - point: Worked as a TA for Database Design and helped the student learn and create database systems.
# #         - point: Worked as a TA for Foundations of Data Science and helped the students learn about the basics of Data Science.
# #         - point: Worked as a TA for Data Management and Processing and helped the students learn R and use it for solving Data Science problems.

  # Education
  disable_education: false
  education:
    - degree: "Master of Science"
      branch: "Data Science"
      university: "Northeastern University"
      startedyear: "2019"
      graduation: "2021"
    - degree: "Bachelor of Engineering"
      branch: "Electronics and Communication"
      university: "Rajiv Gandhi Proudyogiki Vishwavidyalaya"
      startedyear: "2012"
      graduation: "2016"
   

  # Projects
  disable_projects: false
  projects:
    - name: "Walmart Sales Forecasting"
      img: /images/project.jpg
      githublink: "https://github.com/sonaljain2212/Walmart-Sales-Forecasting"
      featuredlink: "/"
      description: " Walmart Sales Forecasting will present the right methodologies to analyze time-series sales data and predict 28 days ahead point forecasts for the company to take strategic decisions based on the predictions. "
    - name: "Healthcare Entity and Relationship Extraction on Clinicaldata"
      img: /images/project.jpg
      githublink: "https://github.com/sonaljain2212/Healthcare-Entity-and-Relationship-Extraction-on-Clinicaldata"
      featuredlink: "/"
      description: "This project aims to perform Named entity and Relationship extraction on EHR data and find the latent information present in the data using topic modeling and Market basket analysis."
    - name: "TV show character prediction using NLP"
      img: /images/project.jpg
      githublink: "https://github.com/sonaljain2212/TV-show-character-prediction-using-NLP"
      featuredlink: "/"
      description: "This project aims to predicts \"Which Character are You?\" as to which Seinfeld character would be most likely to say the sentence/joke that was entered."
    - name: "Credit Card Fraud Detection"
      img: /images/project.jpg
      githublink: "https://github.com/sonaljain2212/Credit-Card-Fraud-Detection"
      featuredlink: "/"
      description: "Credit card fraud is a form of identity theft in which criminals make purchases or obtain cash advances using a credit card account assigned to you. This project aim to accurate predict fraud transactions."
    - name: "Customer churn prediction"
      img: /images/project.jpg
      githublink: "https://github.com/sonaljain2212/Customer-Churn-prediction"
      featuredlink: "/"
      description: "This project aim to predict the churn and retention rate for a job board dataset."

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
 

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "sonaljain2212@gmail.com"

  # Footer
  socialiconfooter: false
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
  
